Repository YAPP-Github/21st-ALL-Rounder-Team-3-Web, pull requests merged in 2023-02, with the labels that each got.

#10 디자인 시스템 추가/수정 사항 구현
  package.json
  src/App.tsx
  src/components/common/Badge.tsx
  src/components/common/Button.tsx
  src/components/common/DateForm.tsx
  src/components/common/Divider.tsx
  src/components/common/DropDown.tsx
  src/components/common/Input.tsx
  src/components/common/TextArea.tsx
  src/components/common/TopBar.tsx
  src/components/layout/FixedBottomButtonLayout.tsx
  src/components/task/BadgeWithDescription.tsx
  src/components/task/CheckStatus.tsx
  src/components/task/TaskDescription.tsx
  src/components/task/TaskHeader.tsx
  src/components/task/TaskManagerProfile.tsx
  src/custom.d.ts
  src/styled.d.ts
  src/styles/Typo.ts
  src/styles/colors.ts
  src/styles/theme.ts
  webpack.config.js
  yarn.lock
Labels: feature

#11 [feat] Input withError 추가
  src/components/common/Input.tsx
Labels: feature, bug

#12 [AR3-20] 팀원, 본인 업무 상세 화면 분리; URL, FeedbackResult 컴포넌트구현
  src/assets/icons/IconAlertCircle.svg
  src/assets/icons/IconCheckContained.svg
  src/assets/icons/IconCircleClose.svg
  src/assets/icons/IconLink.svg
  src/assets/icons/index.tsx
  src/components/common/Badge.tsx
  src/components/common/DateForm.tsx
  src/components/task/BadgeWithDescription.tsx
  src/components/task/CheckStatus.tsx
  src/components/task/FeedbackResult.tsx
  src/components/task/TaskBasicDescription.tsx
  src/components/task/TaskHeader.tsx
  src/components/task/URL.tsx
  src/constants/URLConstants.ts
  src/pages/MyTaskDetailPage.tsx
  src/pages/OthersTaskDetailPage.tsx
  src/pages/TaskDetailPage.tsx
  src/routConfig.tsx
  src/utils/formatDate.tsx
Labels: feature, chore

#13 피드백 페이지 구현 / BottomSheet 구현 / axios 기본 세팅
  package.json
  src/App.tsx
  src/assets/icons/IconCircleClose.svg
  src/assets/icons/IconClose.svg
  src/assets/icons/index.tsx
  src/components/bottomSheet/TaskFeedbackBottomSheet.tsx
  src/components/common/BottomSheet.tsx
  src/constants/URLConstants.ts
  src/constants/feedback.ts
  src/core/atoms/atoms.ts
  src/core/hooks/useBottomSheet.ts
  src/core/queries/sendFeedbackMutation.ts
  src/core/services/httpService.ts
  src/index.tsx
  src/pages/TaskFeedbackPage.tsx
  src/routeConfig.tsx
  webpack.config.js
  yarn.lock
Labels: feature, chore

#14 업무 생성 페이지 구현 / 관련 query 구현 / bridge navigate 추가
  src/components/common/DateForm.tsx
  src/components/common/DropDown.tsx
  src/components/task/TaskBasicDescription.tsx
  src/core/queries/queryKeys.ts
  src/core/queries/useParticipantsQuery.ts
  src/core/queries/useSendCreateTaskMutation.ts
  src/custom.d.ts
  src/pages/TaskCreatePage.tsx
  src/pages/TaskEditPage.tsx
  src/routeConfig.tsx
  src/utils/formatDate.tsx
Labels: feature, chore
